### ISSUE TITLE
Issues with yarn install. I can't run the next app locally on my Windows machine

### ISSUE THREAD

**Issue by YasBenAll** [nandorojo/solito#354]
I deployed the starter project to vercel, [as shown in the documentation](https://solito.dev/starter), but after installing the dependencies in the root folder using ```yarn``` and trying to run the next app using ```yarn dev```,  to run the next app on my own machine, I ran into some issues.

```
C:\Users\Yassi\Documents\GitHub\app>yarn install
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @dripsy/core@npm:3.8.1 doesn't provide react (p39ef1), requested by @react-native-community/hooks
➤ YN0002: │ @dripsy/core@npm:3.8.1 doesn't provide react-native (p4982e), requested by @react-native-community/hooks
➤ YN0002: │ @expo/cli@npm:0.6.2 doesn't provide expo-modules-autolinking (pe2591), requested by @expo/prebuild-config
➤ YN0002: │ @expo/webpack-config@npm:0.17.3 doesn't provide expo (p28ee1), requested by expo-pwa
➤ YN0002: │ app@workspace:packages/app doesn't provide @babel/core (pf955d), requested by react-native-reanimated
➤ YN0002: │ app@workspace:packages/app doesn't provide react (pa3194), requested by @react-navigation/native-stack
➤ YN0002: │ app@workspace:packages/app doesn't provide react (pf0099), requested by @react-navigation/native
➤ YN0002: │ app@workspace:packages/app doesn't provide react (pccf59), requested by react-native-reanimated
➤ YN0002: │ app@workspace:packages/app doesn't provide react-native (p48ecd), requested by @react-navigation/native-stack
➤ YN0002: │ app@workspace:packages/app doesn't provide react-native (pd7871), requested by @react-navigation/native
➤ YN0002: │ app@workspace:packages/app doesn't provide react-native (p8d7a1), requested by react-native-reanimated
➤ YN0002: │ app@workspace:packages/app doesn't provide react-native-safe-area-context (p5aecf), requested by @react-navigation/native-stack
➤ YN0002: │ app@workspace:packages/app doesn't provide react-native-screens (p1dbcd), requested by @react-navigation/native-stack
➤ YN0002: │ babel-preset-expo@npm:9.2.0 doesn't provide @babel/core (p2866c), requested by @babel/plugin-proposal-decorators
➤ YN0002: │ babel-preset-expo@npm:9.2.0 doesn't provide @babel/core (p15336), requested by @babel/plugin-transform-react-jsx
➤ YN0002: │ babel-preset-expo@npm:9.2.0 doesn't provide @babel/core (p793ac), requested by @babel/preset-env
➤ YN0002: │ babel-preset-expo@npm:9.3.0 doesn't provide @babel/core (p0df83), requested by @babel/plugin-proposal-object-rest-spread
➤ YN0002: │ babel-preset-expo@npm:9.3.0 doesn't provide @babel/core (p645fb), requested by @babel/plugin-proposal-decorators
➤ YN0002: │ babel-preset-expo@npm:9.3.0 doesn't provide @babel/core (p0e101), requested by @babel/plugin-transform-react-jsx
➤ YN0002: │ babel-preset-expo@npm:9.3.0 doesn't provide @babel/core (pb43f2), requested by @babel/preset-env
➤ YN0002: │ expo-asset@npm:8.9.0 doesn't provide expo (pa7bf1), requested by expo-constants
➤ YN0002: │ expo-asset@npm:8.9.0 doesn't provide expo (pcf5ad), requested by expo-file-system
➤ YN0002: │ expo-linking@npm:3.2.2 doesn't provide expo (pd9e25), requested by expo-constants
➤ YN0002: │ expo-splash-screen@npm:0.18.1 [72208] doesn't provide expo-modules-autolinking (p45296), requested by @expo/prebuild-config
➤ YN0002: │ moti@npm:0.20.0 [f87a9] doesn't provide react (pbc0e2), requested by framer-motion
➤ YN0002: │ moti@npm:0.20.0 [f87a9] doesn't provide react-dom (p35671), requested by framer-motion
➤ YN0002: │ next-app@workspace:apps/next doesn't provide eslint (p27b06), requested by eslint-config-next
➤ YN0060: │ next-app@workspace:apps/next provides next (pb6520) with version 13.0.1, which doesn't satisfy what @expo/next-adapter requests
➤ YN0060: │ next-app@workspace:apps/next provides react (pcce7b) with version 18.2.0, which doesn't satisfy what @expo/next-adapter requests
➤ YN0002: │ next-app@workspace:apps/next doesn't provide react-native-web (p39316), requested by @expo/next-adapter
➤ YN0002: │ next-app@workspace:apps/next doesn't provide webpack (p9164a), requested by next-fonts
➤ YN0002: │ next-app@workspace:apps/next doesn't provide webpack (p051c4), requested by next-images
➤ YN0002: │ react-native-codegen@npm:0.71.5 doesn't provide @babel/preset-env (pdcb72), requested by jscodeshift
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 377ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs-parser@npm:21.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:13.3.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:15.4.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:17.7.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 1m 4s
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed in 0s 237ms
➤ YN0000: Done with warnings in 1m 4s
```

```
C:\Users\Yassi\Documents\GitHub\app>yarn web 
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error: @expo/next-adapter tried to access @expo/config, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @expo/config (via "@expo\config\paths")
Required by: @expo/next-adapter@virtual:1e21ed5e542f04ac0725f80f20538bd288a2542912556a71424e0ef86756859fcedbc2507675d93c28d09cc2e230d8793e424a169e257d21ba5cb20fce2d2238#npm:4.0.13 (via C:\Users\Yassi\Documents\GitHub\app\.yarn\__virtual__\@expo-next-adapter-virtual-644de5c67a\0\cache\@expo-next-adapter-npm-4.0.13-3a58c94e90-b3cb86af18.zip\node_modules\@expo\next-adapter\build\)

Require stack:
- C:\Users\Yassi\Documents\GitHub\app\.yarn\__virtual__\@expo-next-adapter-virtual-644de5c67a\0\cache\@expo-next-adapter-npm-4.0.13-3a58c94e90-b3cb86af18.zip\node_modules\@expo\next-adapter\build\withExpo.js
- C:\Users\Yassi\Documents\GitHub\app\.yarn\__virtual__\@expo-next-adapter-virtual-644de5c67a\0\cache\@expo-next-adapter-npm-4.0.13-3a58c94e90-b3cb86af18.zip\node_modules\@expo\next-adapter\build\index.js
- C:\Users\Yassi\Documents\GitHub\app\apps\next\next.config.js
    at Function.require$$0.Module._resolveFilename (C:\Users\Yassi\Documents\GitHub\app\.pnp.cjs:31208:13)
    at Function.mod._resolveFilename (C:\Users\Yassi\Documents\GitHub\app\.yarn\__virtual__\next-virtual-4e12e97bba\0\cache\next-npm-13.0.1-fffb8ad028-50f5f19a9b.zip\node_modules\next\dist\build\webpack\require-hook.js:23:32)
    at Function.require$$0.Module._load (C:\Users\Yassi\Documents\GitHub\app\.pnp.cjs:31058:42)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Yassi\Documents\GitHub\app\.yarn\__virtual__\@expo-next-adapter-virtual-644de5c67a\0\cache\@expo-next-adapter-npm-4.0.13-3a58c94e90-b3cb86af18.zip\node_modules\@expo\next-adapter\build\withExpo.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require$$0.Module._extensions..js (C:\Users\Yassi\Documents\GitHub\app\.pnp.cjs:31252:33)
    at Module.load (node:internal/modules/cjs/loader:981:32)

```

Am I missing something here? How do I fix? I can't run the next app locally on my machine now.

**Comment by nandorojo** [comment]
I just fixed this for the existing starter apps. So you could run the starter app script again, or see the upgrade guide here: https://github.com/nandorojo/solito/releases/tag/v3.1.0

**Comment by aflatoon2874** [comment]
> I just fixed this for the existing starter apps. So you could run the starter app script again, or see the upgrade guide here: https://github.com/nandorojo/solito/releases/tag/v3.1.0

Still doesn't work. I created new application today on linux from the updated template. I am facing the same issue.
